/**
 * DietCoverAttributions — small footer block crediting the photographers
 * whose Unsplash images we use as diet plan thumbnails. Required by the
 * Unsplash API guidelines (https://help.unsplash.com/en/articles/2511315).
 *
 * The attribution map is generated by scripts/generateDietCovers.mjs and
 * served as a static JSON file at /diets/covers/attributions.json. We fetch
 * it lazily so the component still mounts cleanly before the script has
 * been run (empty list → nothing renders).
 */
import { useEffect, useState } from 'react';

interface Attribution {
    tier: string;
    photoId: string;
    photographerName: string;
    photographerUrl: string;
    photoUrl: string;
    unsplashUrl: string;
}

export function DietCoverAttributions() {
    const [entries, setEntries] = useState<Attribution[]>([]);

    useEffect(() => {
        let cancelled = false;
        fetch('/diets/covers/attributions.json')
            .then(r => (r.ok ? r.json() : {}))
            .then((data: Record<string, Attribution>) => {
                if (cancelled) return;
                setEntries(Object.values(data ?? {}));
            })
            .catch(() => { /* silent — attributions are best-effort */ });
        return () => { cancelled = true; };
    }, []);

    if (entries.length === 0) return null;

    // Dedup by photographer (a single photographer may appear across tiers).
    const byPhotographer = new Map<string, Attribution>();
    for (const e of entries) {
        if (!byPhotographer.has(e.photographerName)) byPhotographer.set(e.photographerName, e);
    }
    const credits = Array.from(byPhotographer.values());

    return (
        <div className="text-[10px] font-label tracking-[0.14em] uppercase text-on-surface/40 leading-relaxed pt-6 mt-6 border-t border-outline-variant/20">
            Cover photos by {credits.map((c, i) => (
                <span key={c.photoId}>
                    <a
                        href={c.photographerUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="hover:text-primary transition-colors"
                    >
                        {c.photographerName}
                    </a>
                    {i < credits.length - 1 ? ', ' : ''}
                </span>
            ))} on{' '}
            <a
                href={credits[0]?.unsplashUrl ?? 'https://unsplash.com/'}
                target="_blank"
                rel="noopener noreferrer"
                className="hover:text-primary transition-colors"
            >
                Unsplash
            </a>
        </div>
    );
}
